[package]
name = "RedAlt-SteamUp-Creator"
version = "2.0.0-alpha.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"

[dependencies]
aes-gcm = "0.10.3"
crossbeam-channel = "0.5.15"
eframe = "0.31.1"
egui_file = "0.22.1"
reqwest = "0.12.22"
self_update = { version = "0.42.0", features = ["default", "compression-zip-deflate"]}
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.140"
tempfile = "3.20.0"
which = "8.0.0"
